export const TOTALORDERGET_REQUEST = "TOTALORDERGET_REQUEST"
export const TOTALORDERGET_SUCCESS = "TOTALORDERGET_SUCCESS"
export const TOTALORDERGET_FAILURE = "TOTALORDERGET_FAILURE"


export const DELETE_TOTALORDER="DELETE_TOTALORDER"
export const ADDTO_TOTALORDER="ADDTO_TOTALORDER"
export const UPDATE_TOTALORDER="UPDATE_TOTALORDER"