export const ORDERGET_REQUEST = "ORDERGET_REQUEST"
export const ORDERGET_SUCCESS = "ORDERGET_SUCCESS"
export const ORDERGET_FAILURE = "ORDERGET_FAILURE"


export const DELETE_ORDER="DELETE_ORDER"
export const ADDTO_ORDER="ADDTOORDER"
export const UPDATE_ORDER="UPDATE_ORDER"