export const WISHLIST_PRODUCT_REQUEST = "WISHLIST_PRODUCT_REQUEST"
export const WISHLIST_PRODUCT_SUCCESS = "WISHLIST_PRODUCT_SUCCESS"
export const WISHLIST_PRODUCT_FAILURE = "WISHLIST_PRODUCT_FAILURE"